name: links on mastodon 
on:
  schedule:
    - cron: '0 10,22 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
          MASTODON_USER_NAME: ${{ secrets.MASTODON_USER_NAME }}
        run: |
          python update/run.py
      - name: commit
        run: |
          git config --global user.email "arnicas@gmail.com"
          git config --global user.name "mastodon_links"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] update"; git push -q "https://$GH_TOKEN@github.com/arnicas/mastodon_links.git" main)
